### ISSUE TITLE
Sally test scripts broken ?

### ISSUE THREAD

**Issue by dohmatob** [rieck/sally#16]
For example, the script `test_options.sh` exits with (error) status 1.
elvis@middle-earth:~/CODE/FORKED/sally/tests$ ./test_options.sh 
> 1::1,2::1,3::1,6::1,7::1,8::1,10::1,14::1,15::1,21::1,24::1,27::1,28::1,29::1,30::1,32::1 # line0
> 2::1,3::1,9::1,16::1,18::1,24::1,25::1,26::1,28::1,29::1,31::1 # line1
> 5::1,9::1,11::1,13::1,15::1,17::1,18::1,22::1,25::1,30::1,31::1 # line2
> 2::1,6::1,7::1,9::1,11::1,12::1,16::1,17::1,19::1,21::1,25::1,26::1,27::1,28::1,29::1,32::1 # line3
> 1::1,5::1,8::1,11::1,15::1,16::1,17::1,20::1,21::1,22::1,23::1,25::1 # line4
> 1::1,2::1,5::1,7::1,9::1,13::1,15::1,16::1,19::1,27::1,28::1,30::1 # line5
> 6::1,9::1,12::1,13::1,14::1,18::1,19::1,20::1,23::1,29::1,31::1 # line6
> 2::1,6::1,7::1,9::1,11::1,12::1,16::1,17::1,19::1,21::1,23::1,25::1,31::1 # line7
elvis@middle-earth:~/CODE/FORKED/sally/tests$ echo $?
1

**Comment by rieck** [comment]
Does this also happen if you run `make check` on the root directory of the project?

**Comment by dohmatob** [comment]
Yes, this is what triggered the initial problem. Trying to troubleshoot the problem, I found that the test_options.sh (for example), does some computation, but it seems the output is not what is expected by the test writer (they do a diff ...). Indeed,

elvis@middle-earth:~/CODE/FORKED/sally$ make check

PASS: test_fhash
PASS: test_fvec
PASS: test_embed
PASS: test_ngrams
FAIL: test_options.sh
FAIL: test_configs.sh
make[4]: Entering directory `/home/elvis/CODE/FORKED/sally/tests'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/elvis/CODE/FORKED/sally/tests'

**Comment by rieck** [comment]
Can you provide more information on your build environment and the version of Sally. I cannot reproduce the problem with `head` on Ubuntu Linux 64bit and Mac OS X. 

You can also use the pre-compiled packages of Sally from `launchpad` and `homebrew` btw.

**Comment by dohmatob** [comment]
My box is ubuntu 14.04 (32-bit linux). I built sally from master (hash: 25e9eae4b32fd2200a2e6048e99ccd0f6da47979) with 
`./configure --enable-md5hash --prefix=/home/elvis/.local`

**Comment by rieck** [comment]
Okay. If you drop `--enable-md5hash` it should work. There is simply no test case for MD5-based features.

**Comment by dohmatob** [comment]
OK, indeed the `--enable-md5hash` flag is indeed the problem. Thanks.
