### ISSUE TITLE
PRISMA conf file (asap dataset) out of sync with new sally API ?

### ISSUE THREAD

**Issue by dohmatob** [rieck/sally#17]
elvis@middle-earth:~/CODE/FORKED/PRISMA/inst/extdata$ sally -c asap.cfg -g bytes asap.raw asap.sally

`Error: Your configuration is missing the new 'granularity' parameter. Please consult the manual page and upgrade your configuration. (sally_load_config)`

**PRISM git hash:** 22bb514539197a174db1b82025317fab118a4487
**Sally git hash:** 25e9eae4b32fd2200a2e6048e99ccd0f6da47979

Related to issue https://github.com/tammok/PRISMA/issues/1 (PRISM).

**Comment by dohmatob** [comment]
FWIW: My `git bisect` tells me the commit 96c9e6741400a6003e56deace54ffccce114d4ea is the last commit which still supported the PRISM asap conf file format.

**Comment by rieck** [comment]
Okay. This is more a tammok/PRISMA#1 issue.
