### ISSUE TITLE
No prediction

### ISSUE THREAD

**Issue by arjunmenon** [rieck/sally#19]
I ran the predict using the same reuters.zip dataset
```
$ ./liblinear-2.1/predict -b 1 reuters.zip  reuters.libsvm out
unknown text in model file: [38854]
can't open model file reuters.libsvm
```
I dont know what I am missing here.

Can you provide a sample predict example please.

**Comment by rieck** [comment]
What are you trying to achieve? Sally is a tool for extracting feature vectors from strings. In your example, you are using the plain zip archive as input to the classifier and the feature vectors as model. This doesn't make any sense.

See
```linear-predict
Usage: predict [options] test_file model_file output_file
options:
-b probability_estimates: whether to output probability estimates, 0 or 1 (default 0); currently for logistic regression only
-q : quiet mode (no outputs)```

**Comment by arjunmenon** [comment]
For the example you have described for reuters dataset, can you provide a demo how to run the predict for a simple news headline?
This is a reuters headline for today - `Confronted by market doubts, Federal Reserve drove March rate rise expectations`
It would be much clear.

**Comment by rieck** [comment]
I think you can do this yourself. 

### Training
1. Collect a set of headlines from a fixed set of topics.
2. Apply Sally to convert your headlines into feature vectors.
3. Use `train` of Liblinear to create a SVM model

### Prediction
1. Collect a set of new headlines
2. Apply Sally to convert your headlines into feature vectors.
3. Use `predict` of Liblinear to assign each headline to a topic
